/*
 * Nonogram Odyssey service worker — generated by scripts/build-service-worker.ts.
 * Do not edit by hand; it is rebuilt on every production build.
 */
const VERSION = "59d229420a3f";
const CACHE = 'nonogram-odyssey-' + VERSION;
const SCOPE = "/";
const PRECACHE = [
  "/assets/index-BDSxrUf_.css",
  "/assets/index-bLRKa0Uh.js",
  "/assets/solver-C1qsi3rx.js",
  "/catalog/chapter-01.json",
  "/catalog/chapter-02.json",
  "/catalog/chapter-03.json",
  "/catalog/chapter-04.json",
  "/catalog/chapter-05.json",
  "/catalog/chapter-06.json",
  "/catalog/chapter-07.json",
  "/catalog/chapter-08.json",
  "/catalog/chapter-09.json",
  "/catalog/chapter-10.json",
  "/catalog/chapter-11.json",
  "/catalog/chapter-12.json",
  "/catalog/chapter-13.json",
  "/catalog/chapter-14.json",
  "/catalog/chapter-15.json",
  "/catalog/chapter-16.json",
  "/catalog/chapter-17.json",
  "/catalog/chapter-18.json",
  "/catalog/chapter-19.json",
  "/catalog/chapter-20.json",
  "/catalog/chapter-21.json",
  "/catalog/chapter-22.json",
  "/catalog/chapter-23.json",
  "/catalog/chapter-24.json",
  "/catalog/chapter-25.json",
  "/catalog/chapter-26.json",
  "/catalog/chapter-27.json",
  "/catalog/chapter-28.json",
  "/catalog/chapter-29.json",
  "/catalog/chapter-30.json",
  "/catalog/chapter-31.json",
  "/catalog/chapter-32.json",
  "/catalog/chapter-33.json",
  "/catalog/chapter-34.json",
  "/catalog/chapter-35.json",
  "/catalog/chapter-36.json",
  "/catalog/chapter-37.json",
  "/catalog/chapter-38.json",
  "/catalog/chapter-39.json",
  "/catalog/chapter-40.json",
  "/catalog/chapter-41.json",
  "/catalog/chapter-42.json",
  "/catalog/chapter-43.json",
  "/catalog/chapter-44.json",
  "/catalog/chapter-45.json",
  "/catalog/chapter-46.json",
  "/catalog/chapter-47.json",
  "/catalog/chapter-48.json",
  "/catalog/chapter-49.json",
  "/catalog/chapter-50.json",
  "/catalog/index.json",
  "/icons/apple-touch-icon.png",
  "/icons/favicon-32.png",
  "/icons/icon-192.png",
  "/icons/icon-512.png",
  "/icons/icon-maskable-512.png",
  "/index.html",
  "/manifest.webmanifest"
];

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(CACHE).then(async (cache) => {
      // Bounded concurrency: firing 60+ requests at once makes some of them
      // fail on constrained connections, and cache.addAll would then abort the
      // whole install. Each entry is added individually, in small batches, and
      // is retried once before being left for the runtime handler to fetch.
      const CONCURRENCY = 6;
      const queue = PRECACHE.slice();

      const addOne = async (url) => {
        for (let attempt = 0; attempt < 2; attempt += 1) {
          try {
            await cache.add(new Request(url, { cache: 'reload' }));
            return;
          } catch (error) {
            if (attempt === 1) return;
          }
        }
      };

      const workers = [];
      for (let i = 0; i < CONCURRENCY; i += 1) {
        workers.push(
          (async () => {
            for (;;) {
              const url = queue.shift();
              if (url === undefined) return;
              await addOne(url);
            }
          })(),
        );
      }
      await Promise.all(workers);
    }),
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    (async () => {
      const names = await caches.keys();
      await Promise.all(
        names
          .filter((name) => name.startsWith('nonogram-odyssey-') && name !== CACHE)
          .map((name) => caches.delete(name)),
      );
      await self.clients.claim();
    })(),
  );
});

self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') self.skipWaiting();
});

/*
 * Every asset here is content-hashed or versioned with the cache name, so the
 * URL alone identifies the response. ignoreVary matters: static hosts commonly
 * send "Vary: Origin", and without it a lookup misses whenever the page's
 * request headers differ from the ones used during precaching — which silently
 * breaks offline mode while the cache looks perfectly well populated.
 */
const MATCH_OPTIONS = { ignoreVary: true };

async function networkFirst(request) {
  const cache = await caches.open(CACHE);
  try {
    const response = await fetch(request);
    if (response && response.ok) cache.put(request, response.clone());
    return response;
  } catch (error) {
    const cached = await cache.match(request, MATCH_OPTIONS);
    if (cached) return cached;
    throw error;
  }
}

async function cacheFirst(request) {
  const cache = await caches.open(CACHE);
  const cached = await cache.match(request, MATCH_OPTIONS);
  if (cached) return cached;
  const response = await fetch(request);
  if (response && response.ok) cache.put(request, response.clone());
  return response;
}

self.addEventListener('fetch', (event) => {
  const request = event.request;
  if (request.method !== 'GET') return;

  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;
  if (!url.pathname.startsWith(SCOPE)) return;

  // Navigations: network first so a fresh deployment is picked up promptly,
  // falling back to the cached shell when offline.
  if (request.mode === 'navigate') {
    event.respondWith(
      networkFirst(request).catch(async () => {
        const cache = await caches.open(CACHE);
        const shell = await cache.match(SCOPE + 'index.html', MATCH_OPTIONS);
        return shell || Response.error();
      }),
    );
    return;
  }

  // Everything else is content-hashed or versioned with the cache, so serving
  // from the cache first is both correct and fast — including the catalog.
  event.respondWith(cacheFirst(request));
});
